stages:
  - build
  - publish
  - deploy

include:
  - project: 'lvckyworld-docker/gitlab-ci-rezept'
    file:
      - '/deployment/.rsync.yml'
  - component: git.lvckyworld.dev/pipeline-components/node-package-manager/npm-install@~latest
  - component: git.lvckyworld.dev/pipeline-components/node-package-manager/publish-npm-package@~latest

npm install:
  extends: .npm install
  script:
    - ls -la
    - npm run build
    - npm run compodoc
  only:
    - merge_requests
    - /^(deploy-[a-z]{3,}-)\d{8}.\d{4}$/
  cache:
    paths:
      - ./documentation/
      - ./lib/

publish to npm:
  extends: .publish to npm
  only:
    - /^(deploy-prod-)\d{8}.\d{4}$/

deploy documentation:
  stage: deploy
  extends: .deploy-rsync
  needs:
    - publish to npm
  environment:
    name: 'production'
    url: https://docs.lvckyworld.net/marina-api-sdk
  variables:
    SERVER: 'gamma.lvckyworld.dev'
    SERVER_PORT: 22
    SERVER_USERNAME: 'root'
    SERVER_PATH: '/var/www/vhosts/lvckyworld.net/docs.lvckyworld.net/marina-api-sdk'
    RSYNC_OPTIONS: '--delete'
    FOLDER_TO_SYNC: './documentation/'
  before_script:
    - ls -la ${FOLDER_TO_SYNC}
  script:
    # deploy using rsync jobs script
    - !reference [ .deploy-rsync, script ]
    - |
      runssh() {
        echo "$@" | ssh -p $SERVER_PORT $SERVER_USERNAME@$SERVER "(cd $SERVER_PATH || true && export CURRENTDIR=${CURRENTDIR} && 
        export SERVER_PATH=${SERVER_PATH} && export CI_COMMIT_SHORT_SHA=${CI_COMMIT_SHORT_SHA} && bash -s)"
      }

    # list the files on the server
    - echo "FILES FROM SERVER"
    - runssh ls -la

    # move to the correct directory
    - mv documentation/* .
    - rm -rf documentation

    # correct ownership
    - runssh plesk repair fs -y -v
  cache:
    key: ${CI_COMMIT_REF_SLUG}-${CI_PROJECT_ID}
    paths:
      - ./documentation
    policy: pull
  only:
    - /^(deploy-prod-)\d{8}.\d{4}$/